sudo systemctl enable bluetooth.service
sudo systemctl enable cups.service
sudo systemctl enable greetd.service
sudo systemctl enable libvirtd.service
sudo systemctl enable libvirtd.socket
sudo systemctl enable power-profiles-daemon.service
sudo systemctl enable rtkit-daemon.service
sudo systemctl enable systemd-networkd.service
sudo systemctl enable systemd-resolved.service
sudo systemctl enable systemd-timesyncd.service
sudo systemctl enable systemd-zram-setup@zram0.service
