bar:
  height: 24
  location: top
  foreground: FFFFFFFF
  background: 202020FF
  font: Inter:style=Medium:pixelsize=12
  left:
    - i3:
        sort: ascending
        content:
          "":
            map:
              conditions:
                state == "focused":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      stack:
                        - background: {color: 303030FF}
                state == "unfocused":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    on-click: "swaymsg --quiet workspace {name}"
                state == "invisible":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    on-click: "swaymsg --quiet workspace {name}"
                state == "urgent":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      background: {color: FF6961FF}
                    on-click: "swaymsg --quiet workspace {name}"
  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map:
                  conditions:
                    ~muted:
                       - string:
                           text: "\uf028"
                           font: Font Awesome 6 Free:pixelsize=12
                           on-click:
                             left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                             wheel-up: "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"
                             wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
                       - string:
                           text: "{cubic_volume}%"
                           left-margin: 3
                           right-margin: 15
                    muted:
                      - string:
                          text: "\uf6a9"
                          font: Font Awesome 6 Free:pixelsize=12
                          on-click:
                             left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                             wheel-up: "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"
                             wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
                      - string:
                          text: "{cubic_volume}%"
                          left-margin: 3
                          right-margin: 15
    - battery:
        name: "BAT1"
        content:
          - string:
              text: "\uf240"
              font: Font Awesome 6 Free:pixelsize=12
          - string:
              text: "{capacity}%"
              left-margin: 3
              right-margin: 15
    - network:
        content:
          map:
            conditions:
              name == "wlan0":
                - string:
                    text: "\uf1eb"
                    font: Font Awesome 6 Free:pixelsize=12
                - string:
                    text: "{ipv4}"
                    left-margin: 3
                    right-margin: 15
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          - string:
              text: "\uf133"
              font: Font Awesome 6 Free:style=Solid:pixelsize=12
          - string:
              text: "{date}"
              left-margin: 3
              right-margin: 15
          - string:
              text: "\uf017"
              font: Font Awesome 6 Free:style=Solid:pixelsize=12
          - string:
              text: "{time}"
              left-margin: 3
              right-margin: 6
