bar:
  height: 24
  location: top
  foreground: FFFFFFFF
  background: 202020FF
  font: Inter Display Medium:pixelsize=14
  center:
    - i3:
        sort: ascending
        content:
          "":
            map:
              conditions:
                state == focused:
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      stack:
                        - background: {color: 303030FF}
                        - underline: {size: 2, color: FFFFFFFF}
                state == unfocused:
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                state == invisible:
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                state == urgent:
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      background: {color: FF6961FF}
  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map:
                  conditions:
                    ~muted:
                       - string:
                           text: ""
                           font: Font Awesome 6:style=solid
                       - string:
                           text: "{cubic_volume}%"
                           left-margin: 6
                           right-margin: 18
                    muted:
                      - string:
                          text: ""
                          font: Font Awesome 6:style=solid
                      - string:
                          text: "{cubic_volume}%"
                          left-margin: 6
                          right-margin: 18
    - network:
        content:
          map:
            conditions:
              state == up:
                - string:
                    text: ""
                    font: Font Awesome 6:style=solid
                - string:
                    text: "{name}: {ipv4}"
                    left-margin: 6
                    right-margin: 18
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          - string:
              text: ""
              font: Font Awesome 6:style=solid
          - string:
              text: "{date}"
              left-margin: 6
              right-margin: 18
          - string:
              text: ""
              font: Font Awesome 6:style=solid
          - string:
              text: "{time}"
              left-margin: 6
              right-margin: 6
