bar:
  monitor: HDMI-A-1
  height: 24
  location: top
  foreground: FFFFFFFF
  background: 202020FF
  font: Inter:style=Medium:pixelsize=14
  center:
    - i3:
        sort: ascending
        content:
          "":
            map:
              conditions:
                state == "focused":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      stack:
                        - background: {color: 303030FF}
                state == "unfocused":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    on-click: "swaymsg --quiet workspace {name}"
                state == "invisible":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    on-click: "swaymsg --quiet workspace {name}"
                state == "urgent":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      background: {color: FF6961FF}
                    on-click: "swaymsg --quiet workspace {name}"
  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map:
                  conditions:
                    ~muted:
                       - string:
                           text: "\ue050"
                           font: Material Symbols Rounded:style=Medium:pixelsize=18
                           on-click:
                             left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                             wheel-up: "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"
                             wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
                       - string:
                           text: "{cubic_volume}%"
                           left-margin: 3
                           right-margin: 15
                    muted:
                      - string:
                          text: "\ue04f"
                          font: Material Symbols Rounded:style=Medium:pixelsize=18
                          on-click:
                             left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                             wheel-up: "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"
                             wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
                      - string:
                          text: "{cubic_volume}%"
                          left-margin: 3
                          right-margin: 15
    - backlight:
        name: "intel_backlight"
        content:
          - string:
              text: "\ue1ae"
              font: Material Symbols Rounded:style=Medium:pixelsize=18
              on-click:
                wheel-up: "brightnessctl set 2%+"
                wheel-down: "brightnessctl set 2%-"
          - string:
              text: "{percent}%"
              left-margin: 3
              right-margin: 15
    - battery:
        name: "BAT1"
        content:
          map:
            conditions:
              state == "discharging":
                - string:
                    text: "\ue1a4"
                    font: Material Symbols Rounded:style=Medium:pixelsize=18
                - string:
                    text: "{capacity}%"
                    left-margin: 3
                    right-margin: 15
              state == "not charging":
                - string:
                    text: "\ue1a4"
                    font: Material Symbols Rounded:style=Medium:pixelsize=18
                - string:
                    text: "{capacity}%"
                    left-margin: 3
                    right-margin: 15
              state == "full":
                - string:
                    text: "\ue1a4"
                    font: Material Symbols Rounded:style=Medium:pixelsize=18
                - string:
                    text: "{capacity}%"
                    left-margin: 3
                    right-margin: 15
              state == "charging":
                - string:
                    text: "\ue1a3"
                    font: Material Symbols Rounded:style=Medium:pixelsize=18
                - string:
                    text: "{capacity}%"
                    left-margin: 3
                    right-margin: 15
    - network:
        content:
          map:
            conditions:
              name == "wlan0":
                - string:
                    text: "\ue1ba"
                    font: Material Symbols Rounded:style=Medium:pixelsize=18
                - string:
                    text: "{ipv4}"
                    left-margin: 3
                    right-margin: 15
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          - string:
              text: "\ue8df"
              font: Material Symbols Rounded:style=Medium:pixelsize=18
          - string:
              text: "{date}"
              left-margin: 3
              right-margin: 15
          - string:
              text: "\ue8b5"
              font: Material Symbols Rounded:style=Medium:pixelsize=18
          - string:
              text: "{time}"
              left-margin: 3
              right-margin: 6
