bar:
  height: 24
  location: top
  foreground: FFFFFFFF
  background: 202020FF
  font: Inter Display:pixelsize=14:style=Medium
  center:
    - i3:
        sort: ascending
        content:
          "":
            map:
              conditions:
                state == "focused":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      stack:
                        - background: {color: 303030FF}
                        - overline: {size: 2, color: FFFFFFFF}
                state == "unfocused":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                state == "invisible":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                state == "urgent":
                  string:
                    text: "{name}"
                    left-margin: 6
                    right-margin: 6
                    deco:
                      background: {color: FF6961FF}
  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map:
                  conditions:
                    ~muted:
                       - string:
                           text: "\ue050"
                           font: Material Symbols Rounded:pixelsize=16:style=Medium
                       - string:
                           text: "{cubic_volume}%"
                           left-margin: 6
                           right-margin: 15
                    muted:
                      - string:
                          text: "\ue04f"
                          font: Material Symbols Rounded:pixelsize=16:style=Medium
                      - string:
                          text: "{cubic_volume}%"
                          left-margin: 6
                          right-margin: 15
    - backlight:
        name: "intel_backlight"
        content:
          - string:
              text: "\ue518"
              font: Material Symbols Rounded:pixelsize=16:style=Medium
          - string:
              text: "{percent}%"
              left-margin: 6
              right-margin: 15
    - battery:
        name: "BAT1"
        content:
          map:
            conditions:
              state == "discharging":
                - string:
                    text: "\uebdc"
                    font: Material Symbols Rounded:pixelsize=16:style=Medium
                - string:
                    text: "{capacity}%"
                    left-margin: 6
                    right-margin: 15
              state == "not charging":
                - string:
                    text: "\uebdc"
                    font: Material Symbols Rounded:pixelsize=16:style=Medium
                - string:
                    text: "{capacity}%"
                    left-margin: 6
                    right-margin: 15
              state == "full":
                - string:
                    text: "\uebdc"
                    font: Material Symbols Rounded:pixelsize=16:style=Medium
                - string:
                    text: "{capacity}%"
                    left-margin: 6
                    right-margin: 15
              state == "charging":
                - string:
                    text: "\ue1a3"
                    font: Material Symbols Rounded:pixelsize=16:style=Medium
                - string:
                    text: "{capacity}%"
                    left-margin: 6
                    right-margin: 15
    - network:
        content:
          map:
            conditions:
              name == "wlan0":
                - string:
                    text: "\ue63e"
                    font: Material Symbols Rounded:pixelsize=16:style=Medium
                - string:
                    text: "{ipv4}"
                    left-margin: 6
                    right-margin: 15
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          - string:
              text: "\ue8df"
              font: Material Symbols Rounded:pixelsize=16:style=Medium
          - string:
              text: "{date}"
              left-margin: 6
              right-margin: 15
          - string:
              text: "\ue8b5"
              font: Material Symbols Rounded:pixelsize=16:style=Medium
          - string:
              text: "{time}"
              left-margin: 6
              right-margin: 6
